# Generated by Django 4.0.4 on 2022-08-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareboard', '0002_shareboard_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareboard',
            name='images',
        ),
    ]
